name: null
favicon: null
layout_spectrum: 0.2593858817126602
typography_spectrum: 0.7450305812526494
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9378103264607489
  lightness: 0.5535168943461031
  saturation: 0.9814889929257333
  rhythmicContrast: 0.0059967499691993
purpose: []
